version: '3'
services:
    building-login-back:
        image: redis
        container_name: building-login-back
        ports:
            - "6379:6379"

    building-login-front:
        build: ./building_flask
        image: building-login
        container_name: building-login-front
        environment:
            REDIS: building-login-back
        ports:
            - "8080:80"
